CREATE OR REPLACE FUNCTION ttree_insertar(integer)
RETURNS boolean
AS 'MODULE_PATHNAME', 'ttree_insertar'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION ttree_buscar(integer)
RETURNS boolean
AS 'MODULE_PATHNAME', 'ttree_buscar'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION ttree_limpiar()
RETURNS void
AS 'MODULE_PATHNAME', 'ttree_limpiar'
LANGUAGE C STRICT;
